### ISSUE TITLE
Add code to simulator to handle the case that IRF is not specified or only a location is specified

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran-core#3]
When no IRF is specified at all, the simulator should simulate the dataset starting at the timepoint 0, regardless of where the data is simulated, for example:
- if it is simulated from -5 to 5, then from -5 to 0 there will be no signal other than noise. 
- if the data is simulated from 5 to 10, then the range is no longer [0 1] but less (depending on the rate constants). 
- if an IRF vector of lenght 1 is specified, that is the center location that is assumed (i.e. 'mu') in the simulation. in this way the data can be simualted from -5 to 5 where the decay starts at -5 when irfvec(1) && irfvec << -5;

**Comment by SerLap** [comment]
Same is here that would be nice to have that feature in the analysis, If no width is specified it means a deltafunction. No irf i think is less useful that only position

**Comment by joernweissenborn** [comment]
No Irf is the standart case now. See glotaran python.
